premiere erreur :

Error
Traceback (most recent call last):
  File "C:\Users\scawp\OneDrive - EPHEC asbl\Devloppement_Informatique\tp7\TestFraction.py", line 91, in test_is_adjacent_to
    self.assertTrue(f1.is_adjacent_to(f2))
  File "C:\Users\scawp\OneDrive - EPHEC asbl\Devloppement_Informatique\tp7\Fraction_implementer.py", line 119, in is_adjacent_to
    diff = abs(self - other)
TypeError: bad operand type for abs(): 'Fraction'

la methode is_adjacent renvoyait True au lieu de False pour le test f1.is_adjacent_to(f3)
